name: main

on:
  push:
    branches: [ "main" ]
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Build_calculator
        run: g++ Source.cpp Source.cpp Source.cpp -o app
